function find_days_msk = find_days(index, data_datenum, delta_days) 
% function for percentile and seasonal cycle
% index
doy_month = month(data_datenum);
doy_day = day(data_datenum);
doy_year = year(data_datenum);
doy_year_unique = unique(doy_year);
    
bfr_day_start = day(data_datenum(index) - delta_days);
bfr_day_end = day(data_datenum(index) + delta_days);

bfr_month_start = month(data_datenum(index) - delta_days);
bfr_month_end = month(data_datenum(index) + delta_days);
bfr_check_leap = data_datenum(index) - delta_days: ...
    data_datenum(index) + delta_days;
bfr_check_leap_mask = day(bfr_check_leap) == 29 & month(bfr_check_leap) == 2;

if sum(bfr_check_leap_mask) ~= 0
    if data_datenum(index) < datenum(year(data_datenum(index)), 2, 29)
        bfr_day_end = day(data_datenum(index) + delta_days + 1);
        bfr_month_end = month(data_datenum(index) + delta_days + 1);
        
    elseif data_datenum(index) > datenum(year(data_datenum(index)), 2, 29)
        bfr_day_start = day(data_datenum(index) - delta_days - 1);
        bfr_month_start = month(data_datenum(index) - delta_days - 1);
    end
end
find_days_msk = false(size(data_datenum));
for i_year = 1:length(doy_year_unique)
    if datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) < ...
            datenum(doy_year_unique(i_year), month(data_datenum(index)), ...
            day(data_datenum(index))) && ...
            datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) > ...
            datenum(doy_year_unique(i_year), month(data_datenum(index)), ...
            day(data_datenum(index)))
        find_days_msk( ...
            data_datenum >= datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) & ...
            data_datenum <= datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) ...
            ) = true;
    else
        find_days_msk( ...
            data_datenum >= datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) & ...
            data_datenum <= datenum(doy_year_unique(i_year), 12, 31)) = true;
        find_days_msk( ...
            data_datenum <= datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) & ...
            data_datenum >= datenum(doy_year_unique(i_year), 1, 1)) = true;
    end
end
return 
% bfr_day_start = day(data_in.data_datenum(idayofyear) - data_in.delta_days_4_percentile);
% bfr_day_end = day(data_in.data_datenum(idayofyear) + data_in.delta_days_4_percentile);
% 
% bfr_month_start = month(data_in.data_datenum(idayofyear) - data_in.delta_days_4_percentile);
% bfr_month_end = month(data_in.data_datenum(idayofyear) + data_in.delta_days_4_percentile);
% bfr_check_leap = data_in.data_datenum(idayofyear) - data_in.delta_days_4_percentile: ...
%     data_in.data_datenum(idayofyear) + data_in.delta_days_4_percentile;
% bfr_check_leap_mask = day(bfr_check_leap) == 29 & month(bfr_check_leap) == 2;
% 
% if sum(bfr_check_leap_mask) ~= 0
%     if data_in.data_datenum(idayofyear) < datenum(year(data_in.data_datenum(idayofyear)), 2, 29)
%         bfr_day_end = day(data_in.data_datenum(idayofyear) + data_in.delta_days_4_percentile + 1);
%         bfr_month_end = month(data_in.data_datenum(idayofyear) + data_in.delta_days_4_percentile + 1);
%         
%     elseif data_in.data_datenum(idayofyear) > datenum(year(data_in.data_datenum(idayofyear)), 2, 29)
%         bfr_day_start = day(data_in.data_datenum(idayofyear) - data_in.delta_days_4_percentile - 1);
%         bfr_month_start = month(data_in.data_datenum(idayofyear) - data_in.delta_days_4_percentile - 1);
%     end
% end
% bfr_day_msk = false(size(data_in.data_datenum));
% for i_year = 1:length(doy_year_unique)
%     if datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) < ...
%             datenum(doy_year_unique(i_year), month(data_in.data_datenum(idayofyear)), ...
%             day(data_in.data_datenum(idayofyear))) && ...
%             datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) > ...
%             datenum(doy_year_unique(i_year), month(data_in.data_datenum(idayofyear)), ...
%             day(data_in.data_datenum(idayofyear)))
%         bfr_day_msk( ...
%             data_in.data_datenum >= datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) & ...
%             data_in.data_datenum <= datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) ...
%             ) = true;
%         % day -delta falls in the year before
%         %             elseif datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) > ...
%         %                     datenum(doy_year_unique(i_year), month(data_in.data_datenum(idayofyear)), ...
%         %                     day(data_in.data_datenum(idayofyear)))
%     else
%         bfr_day_msk( ...
%             data_in.data_datenum >= datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) & ...
%             data_in.data_datenum <= datenum(doy_year_unique(i_year), 12, 31)) = true;
%         bfr_day_msk( ...
%             data_in.data_datenum <= datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) & ...
%             data_in.data_datenum >= datenum(doy_year_unique(i_year), 1, 1)) = true;
%         % day +delta falls in the year after
%         %             elseif datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) < ...
%         %                     datenum(doy_year_unique(i_year), month(data_in.data_datenum(idayofyear)), ...
%         %                     day(data_in.data_datenum(idayofyear)))
%         %                 bfr_day_msk( ...
%         %                     data_in.data_datenum >= datenum(doy_year_unique(i_year), bfr_month_start, bfr_day_start) & ...
%         %                     data_in.data_datenum <= datenum(doy_year_unique(i_year), 12, 31)) = true;
%         %                 bfr_day_msk( ...
%         %                     data_in.data_datenum <= datenum(doy_year_unique(i_year), bfr_month_end, bfr_day_end) & ...
%         %                     data_in.data_datenum >= datenum(doy_year_unique(i_year), 1, 1)) = true;
%     end
% end