clear all
close all

addpath_matlab_code     = '/Users/jacoposala/Downloads/MHWs_code_DG_JS/';
output_dir              = '/Users/jacoposala/Downloads/MHWs_data_ouput_Aug16/';
% addpath_matlab_code     = '/Users/dogi7244/Downloads/MHWs_code_DG/';
% output_dir              = '/Users/dogi7244/Downloads/MHWs_data_ouput/';

% we first create all the input params we need and then run the code with
% those

list_cases = {...
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % OISST DAILY BOX NEP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % OISST BOX, NEP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_NEP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, NEP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_NEP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, NEP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_NEP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY TEMP BOX NEP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO TEMP BOX, NEP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_NEP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, NEP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_NEP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, NEP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_NEP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY OHC BOX NEP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO OHC BOX, NEP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_NEP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     % ECCO OHC BOX, NEP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_NEP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     % ECCO OHC BOX, NEP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_NEP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_NEP_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % OISST DAILY BOX SWP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % OISST BOX, SWP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_SWP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, SWP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_SWP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, SWP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_SWP','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY TEMP BOX SWP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO TEMP BOX, SWP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_SWP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, SWP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_SWP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, SWP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_SWP','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY OHC BOX SWP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO OHC BOX, SWP, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_SWP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     % ECCO OHC BOX, SWP, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_SWP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     % ECCO OHC BOX, SWP, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_SWP_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_SWP_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % OISST DAILY BOX TASMAN - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % OISST BOX, TASMAN, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_TASMAN','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, TASMAN, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_TASMAN','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     % OISST BOX, TASMAN, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_OISST_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_TASMAN','OISST_1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/OISST/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY TEMP BOX TASMAN - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO TEMP BOX, TASMAN, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_TASMAN','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, TASMAN, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_TASMAN','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     % ECCO TEMP BOX, TASMAN, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_TASMAN','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY OHC BOX TASMAN - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO OHC BOX, TASMAN, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     0, 1992:2017, '_avg_box_TASMAN_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     % ECCO OHC BOX, TASMAN, 1992:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     2, 1992:2017, '_avg_box_TASMAN_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     % ECCO OHC BOX, TASMAN, 1992:2017, tstep_gap = 3
%     set_params_NASAPO_2020_MHWs_ECCO_daily_box(addpath_matlab_code, ...
%     3, 1992:2017, '_avg_box_TASMAN_OHC','1992_2017', ...
%     '/Users/jacoposala/Downloads/MHWs_data/ECCO_daily_TASMAN_avg_box/', output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO MONTHLY TEMP - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO MONTHLY 1993-2016 with budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_1993_2016(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY 1993-2016 with budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_1993_2016(addpath_matlab_code, ...
%     2, output_dir), ...
%     % ECCO MONTHLY 2004-2016 with budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_2004_2016(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY 2004-2016 with budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_2004_2016(addpath_matlab_code, ...
%     2, output_dir), ...
%     % ECCO MONTHLY 1992-2017 without budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_1992_2017_DATA(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY 1992-2017 without budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_zlev1_1992_2017_DATA(addpath_matlab_code, ...
%     2, output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO MONTHLY OHC - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO MONTHLY OHC 1992-2017 without budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_1992_2017_DATA(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY OHC 1992-2017 without budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_1992_2017_DATA(addpath_matlab_code, ...
%     2, output_dir), ...
%     % ECCO MONTHLY OHC 1993-2016 with budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_1993_2016(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY OHC 1993-2016 with budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_1993_2016(addpath_matlab_code, ...
%     2, output_dir), ...
%     % ECCO MONTHLY OHC 2004-2016 with budget terms, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_2004_2016(addpath_matlab_code, ...
%     0, output_dir), ...
%     % ECCO MONTHLY OHC 2004-2016 with budget terms, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_monthly_k0_k5_2004_2016(addpath_matlab_code, ...
%     2, output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % Argo OHC monthly - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % Argo MONTHLY 2004:2016, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_Argo_monthly_OHC(addpath_matlab_code, ...
%     0,2004:2016, output_dir), ...
%     % Argo MONTHLY 2004:2016, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_Argo_monthly_OHC(addpath_matlab_code, ...
%     2,2004:2016, output_dir), ...
%     % Argo MONTHLY 2004:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_Argo_monthly_OHC(addpath_matlab_code, ...
%     0,2004:2017, output_dir), ...
%     % Argo MONTHLY 2004:2017, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_Argo_monthly_OHC(addpath_matlab_code, ...
%     2,2004:2017, output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % OISST MONTHLY - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % OISST MONTHLY, 1992:2017, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_monthly(addpath_matlab_code, ...
%     0, 1992:2017, ...
%     '/Users/jacoposala/Desktop/CU/3.RESEARCH/NASA_project/OISSTv2/DATA/', ...
%     output_dir), ...
%     % OISST MONTHLY, 1993:2016, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_monthly(addpath_matlab_code, ...
%     0, 1993:2016, ...
%     '/Users/jacoposala/Desktop/CU/3.RESEARCH/NASA_project/OISSTv2/DATA/', ...
%     output_dir), ...
%     % OISST MONTHLY, 2004:2016, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_OISST_monthly(addpath_matlab_code, ...
%     0,2004:2016, ...
%     '/Users/jacoposala/Desktop/CU/3.RESEARCH/NASA_project/OISSTv2/DATA/', ...
%     output_dir), ...
%     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % ECCO DAILY - RUN
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
%     % ECCO DAILY, 1992:1994, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily(addpath_matlab_code, ...
%     0, 1992:1994, '_cut', 1992, 1994, 730, ...
%     '/Users/jacoposala/Downloads/ecco_daily_input_files_1992_1994/', ...
%     output_dir), ...
%     % ECCO DAILY, 1992:1994, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily(addpath_matlab_code, ...
%     2, 1992:1994, '_cut', 1992, 1994, 730, ...
%     '/Users/jacoposala/Downloads/ecco_daily_input_files_1992_1994/', ...
%     output_dir), ...
% %     
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % ECCO DAILY OHC - RUN
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
%     % ECCO DAILY OHC, 1992:1994, tstep_gap = 0
%     set_params_NASAPO_2020_MHWs_ECCO_daily_OHC(addpath_matlab_code, ...
%     0, 1992:1994, '_ohc_k0_k5', 1992, 1994, 730, ...
%     '/Users/jacoposala/Downloads/ecco_daily_input_files_1992_1994/', ...
%     output_dir), ...
%     % ECCO DAILY OHC, 1992:1994, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_ECCO_daily_OHC(addpath_matlab_code, ...
%     2, 1992:1994, '_ohc_k0_k5', 1992, 1994, 730, ...
%     '/Users/jacoposala/Downloads/ecco_daily_input_files_1992_1994/', ...
%     output_dir), ...
% % 
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     % OISST DAILY - 
%     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     
    % OISST DAILY, 1992:1994, tstep_gap = 0
    set_params_NASAPO_2020_MHWs_OISST_daily(addpath_matlab_code, ...
    0, 1992:1994, '','sst.day.mean.', ...
    '/Users/jacoposala/Desktop/oisst_daily_input_files/', output_dir), ...
%     % OISST DAILY, 1992:1994, tstep_gap = 2
%     set_params_NASAPO_2020_MHWs_OISST_daily(addpath_matlab_code, ...
%     2, 1992:1994, '','sst.day.mean.', ...
%     '/Users/jacoposala/Desktop/oisst_daily_input_files/', output_dir), ...
    };


for i_list_cases=1:length(list_cases)
    clearvars -except list_cases i_list_cases ...
        addpath_matlab_code output_dir
%     tic;
    params = list_cases{i_list_cases};
    disp(['-------------------------> ' params.fig_path])
    NASAPO_2020_MHWs_detect_and_info_main(params);
%     disp('--------> total time for this run :')
%     toc;
    close all
end







