function params = set_params_ECCO_monthly_zlev1_2004_2016(addpath_matlab_code,...
    num_gap_tsteps_in_event,output_dir)

% _ohc_to50m_k0_k5_1992_2017

% addpath_matlab_code     = '/Users/dogi7244/Downloads/MHWs_code_DG/';
% num_gap_tsteps_in_event = 0;
% output_dir              = '/Users/dogi7244/Downloads/MHWs_data_ouput/';
% Initialize structure
params = struct();
% Set path where the code is
params.addpath_matlab_code = addpath_matlab_code; % DG9Aug '/Users/jacoposala/Downloads/';
% Num of tsteps allowed for a gap within an event
params.num_gap_tsteps_in_event = num_gap_tsteps_in_event; % DG9Aug 2; % 0, 2

% Set the range of years to analyze
params.years = 2004:2016;
% Flag to only use ECCO DATA and NOT the budget terms
params.flag_use_only_DATA = false;
% Set the path for the figure folder
% params.fig_path = '/Users/jacoposala/Downloads/test_ECCO_monthly_Aug1/';
% Create the fig_path dynamically using the extracted years
% DG9Aug (see next line)
params.fig_path = sprintf([output_dir 'ECCO_monthly_heat_zlev01_%d_%d/'], params.years(1), params.years(end));
% Set the z-level
params.zlev = 1;
% Flags for different data sources and options
% params.flag_noaa_oisst = false;
% params.flag_argo = false;
% params.flag_ecco_zint = false;
params.flag_ecco = true;
% params.flag_ecco_daily = false;
% params.flag_noaa_oisst_daily = false;
% params.flag_ecco_daily_box = false;
% params.flag_noaa_oisst_daily_box = false;
% params.flag_fake_data = false;
% Time step delta
params.delta_tstep = 1;
% Percentile for detection
params.percentile = 90;
% Flags for data processing options
params.flag_remove_trend = true;
params.flag_save_MHW_info = true;
params.flag_save_MHW_ave_from_info = true;
% Tag file (empty in this case)
params.tag_file = '';
% User path for ECCO data
params.user_path_ecco = '/Users/jacoposala/Desktop/CU/3.RESEARCH/NASA_project/heatBudgetECCO_jupyter/heat_nc_MONTHLY_files_for_donata/';%'/Users/dogi7244/Downloads/MHWs_data/ECCO_monthly/';
% Filename years
params.year_start_filename = 1993;
params.year_end_filename = 2016;
% Metadata years - just for the files that XC, YC, vol ...
params.tag_years_metadata = '1993_2017';
% Years ACTUALLY in the file
params.year_start_in_file = 1993;
params.year_end_in_file = 2016;
% ECCO data set name
params.ecco_name = 'ECCOv4r4';
% Flag for monthly time series
params.flag_monthly_timeseries = true;
% Flag for monthly time series
params.flag_daily_timeseries = false;
% Number of tiles
params.num_of_tiles = 13;
% Number of points in tiles
params.ecco_num_of_points_in_tiles = 90;
% Number of levels in monthly ECCO data
params.ecco_monthly_num_of_levs = 50;
% Field tag
params.tag_field = 'heat';
% Delta days for percentile
params.delta_days_4_percentile = 5;
% Color axis limits for percentile
params.cax_percentile = [0 6];
% Color axis limits for number of events
params.cax_num_events = [0 30];
% Color axis limits for average duration
params.cax_aveDuration = [0 18];
% Color axis limits for data
params.cax_data = [-6 6];
% Flag for dimension (longitude, latitude, time)
params.flag_dim_lon_lat_time = false;
% Indices for example cases
params.i_all = [5548];
params.j_all = [9];
% Flags for map summary and maps at each time step
params.flag_maps_summary = true;
params.flag_maps_at_each_tstep = false;
% % Call the main function with the parameters
% NASAPO_2020_MHWs_detect_and_info_main(params); % DG9Aug
return

% params = struct( ...
%     'addpath_matlab_code', '/Users/jacoposala/Downloads/', ...
%     'fig_path', '/Users/jacoposala/Downloads/test_ECCO_monthly_Aug1/', ...
%     'years', 1993:2016, ... 
%     'zlev', 1, ...
%     'flag_noaa_oisst', false, ...
%     'flag_argo', false, ...
%     'flag_ecco_zint', false, ...
%     'flag_ecco', true, ...
%     'flag_ecco_daily', false, ...
%     'flag_noaa_oisst_daily', false, ...
%     'flag_ecco_daily_box', false, ...
%     'flag_noaa_oisst_daily_box', false, ...
%     'flag_fake_data', false, ...
%     'delta_tstep', 1, ...
%     'percentile', 90, ...
%     'flag_remove_trend', true, ...
%     'flag_save_MHW_info', true, ...
%     'flag_save_MHW_ave_from_info', true, ...
%     'tag_file', '', ...
%     'user_path_ecco', '/Users/jacoposala/Desktop/CU/3.RESEARCH/NASA_project/heatBudgetECCO_jupyter/heat_nc_MONTHLY_files_for_donata/', ...
%     'year_start_filename', 1993, ...
%     'year_end_filename', 2016, ...
%     'ecco_name', 'ECCOv4r4', ...
%     'flag_monthly_timeseries', true, ...
%     'num_of_tiles', 13, ...
%     'ecco_num_of_points_in_tiles', 90, ...
%     'ecco_monthly_num_of_levs', 50, ...
%     'tag_field', 'heat', ...
%     'delta_days_4_percentile', 5, ...
%     'cax_percentile', [0 6], ...
%     'cax_num_events', [0 30], ...
%     'cax_aveDuration', [0 18], ...
%     'cax_data', [-6 6], ...
%     'flag_dim_lon_lat_time', false, ...
%     'i_all', [5548], ...
%     'j_all', [9], ...
%     'flag_maps_summary', true, ...
%     'flag_maps_at_each_tstep', false);
% NASAPO_2020_MHWs_detect_and_info_main(params);
